theme: jekyll-theme-cayman
title: My Cybersecurity Notes
description: Write-ups, tools, and more.
url: "https://xman-model11.github.io"
baseurl: "mysite"
author: "Xaver"
social: "www.linkedin.com/in/xaversecuritypro"
